/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(app)/dashboard': RouteRecordInfo<'/(app)/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/(app)/learning-path': RouteRecordInfo<'/(app)/learning-path', '/learning-path', Record<never, never>, Record<never, never>>,
    '/(app)/profile': RouteRecordInfo<'/(app)/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/(app)/progress': RouteRecordInfo<'/(app)/progress', '/progress', Record<never, never>, Record<never, never>>,
    '/(app)/settings': RouteRecordInfo<'/(app)/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/(app)/shadowing': RouteRecordInfo<'/(app)/shadowing', '/shadowing', Record<never, never>, Record<never, never>>,
    '/(app)/speaking': RouteRecordInfo<'/(app)/speaking', '/speaking', Record<never, never>, Record<never, never>>,
    '/(app)/subscription': RouteRecordInfo<'/(app)/subscription', '/subscription', Record<never, never>, Record<never, never>>,
    '/(app)/topics': RouteRecordInfo<'/(app)/topics', '/topics', Record<never, never>, Record<never, never>>,
    '/(app)/writing': RouteRecordInfo<'/(app)/writing', '/writing', Record<never, never>, Record<never, never>>,
    '/(auth)/onboarding': RouteRecordInfo<'/(auth)/onboarding', '/onboarding', Record<never, never>, Record<never, never>>,
    '/(auth)/signup': RouteRecordInfo<'/(auth)/signup', '/signup', Record<never, never>, Record<never, never>>,
    '/(marketing)/': RouteRecordInfo<'/(marketing)/', '/', Record<never, never>, Record<never, never>>,
    '/(marketing)/about': RouteRecordInfo<'/(marketing)/about', '/about', Record<never, never>, Record<never, never>>,
    '/(marketing)/pricing': RouteRecordInfo<'/(marketing)/pricing', '/pricing', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(app)/dashboard.vue': {
      routes: '/(app)/dashboard'
      views: never
    }
    'src/pages/(app)/learning-path.vue': {
      routes: '/(app)/learning-path'
      views: never
    }
    'src/pages/(app)/profile.vue': {
      routes: '/(app)/profile'
      views: never
    }
    'src/pages/(app)/progress.vue': {
      routes: '/(app)/progress'
      views: never
    }
    'src/pages/(app)/settings.vue': {
      routes: '/(app)/settings'
      views: never
    }
    'src/pages/(app)/shadowing.vue': {
      routes: '/(app)/shadowing'
      views: never
    }
    'src/pages/(app)/speaking.vue': {
      routes: '/(app)/speaking'
      views: never
    }
    'src/pages/(app)/subscription.vue': {
      routes: '/(app)/subscription'
      views: never
    }
    'src/pages/(app)/topics.vue': {
      routes: '/(app)/topics'
      views: never
    }
    'src/pages/(app)/writing.vue': {
      routes: '/(app)/writing'
      views: never
    }
    'src/pages/(auth)/onboarding.vue': {
      routes: '/(auth)/onboarding'
      views: never
    }
    'src/pages/(auth)/signup.vue': {
      routes: '/(auth)/signup'
      views: never
    }
    'src/pages/(marketing)/index.vue': {
      routes: '/(marketing)/'
      views: never
    }
    'src/pages/(marketing)/about.vue': {
      routes: '/(marketing)/about'
      views: never
    }
    'src/pages/(marketing)/pricing.vue': {
      routes: '/(marketing)/pricing'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
